pull_request_rules:
  - name: request review and label scala-steward's PRs
    conditions:
      - author=scala-steward
    actions:
      request_reviews:
        teams: ["zio-prelude"]
      label:
        add: ["type: dependencies"]
  - name: label scala-steward's breaking PRs
    conditions:
      - author=scala-steward
      - "body~=(labels: library-update, early-semver-major)|(labels: sbt-plugin-update, early-semver-major)"
    actions:
      label:
        add: ["type: breaking"]
  # Auto-approving and auto-merging scala-steward's (and Dependabot's) PRs is now handled by the
  # zio-sbt-ci-generated auto-approve.yml/auto-merge.yml workflows.
