addSbtPlugin("org.scalameta"      % "sbt-scalafmt"   % "2.3.1")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"        % "0.3.7")
addSbtPlugin("com.eed3si9n"       % "sbt-buildinfo"  % "0.9.0")
addSbtPlugin("org.scoverage"      % "sbt-scoverage"  % "1.6.1")
addSbtPlugin("org.scalameta"      % "sbt-mdoc"       % "2.1.1")
addSbtPlugin("ch.epfl.scala"      % "sbt-bloop"      % "1.3.5")
addSbtPlugin("com.eed3si9n"       % "sbt-unidoc"     % "0.4.3")
addSbtPlugin("com.geirsson"       % "sbt-ci-release" % "1.5.0")
